version: '3'

services:
  dns-server:
    build:
      context: ./dns-server/
    ports:
      - "${DNS_SERVER_BIND_IP:-127.0.0.1}:53:53"
      - "${DNS_SERVER_BIND_IP:-127.0.0.1}:53:53/udp"
    environment:
      - resolution_ip=${FORWARDING_SERVER_BIND_IP:-127.2.3.4}
    restart: always

  http-server:
    build:
      context: ./http-server/
    ports:
      - "${FORWARDING_SERVER_BIND_IP:-127.2.3.4}:80:80"
    environment:
      - http_proxy
    restart: always

  https-server:
    build:
      context: ./https-server/
    ports:
      - "${FORWARDING_SERVER_BIND_IP:-127.2.3.4}:443:443"
    environment:
      - https_proxy
    restart: always
