version: '3'

services:
  dns-server:
    build:
      context: ./dns-server/
      args:
        - http_proxy
        - https_proxy
    ports:
      - "${DNS_SERVER_BIND_IP:-127.0.0.1}:53:53"
      - "${DNS_SERVER_BIND_IP:-127.0.0.1}:53:53/udp"
    environment:
      - resolution_ip=${FORWARDING_SERVER_BIND_IP:-127.2.3.4}
      - no_proxy_domains=${NO_PROXY_DOMAINS:-intra.example.com intra.example.net}
    dns:
      - ${ORIGINAL_DNS_SERVER_IP}
    restart: always

  http-server:
    build:
      context: ./http-server/
    ports:
      - "${FORWARDING_SERVER_BIND_IP:-127.2.3.4}:80:80"
    environment:
      - http_proxy
    restart: always

  https-server:
    build:
      context: ./https-server/
    ports:
      - "${FORWARDING_SERVER_BIND_IP:-127.2.3.4}:443:443"
    environment:
      - https_proxy
    restart: always
