version: '3'

services:
  dns-server:
    build:
      context: ./dns-server/
    ports:
      - "${DNSMASQ_BIND_IP_PORT:-127.0.0.1:53}:53"
      - "${DNSMASQ_BIND_IP_PORT:-127.0.0.1:53}:53/udp"
    environment:
      - resolution_ip=${DNSMASQ_RESOLUTION_IP:-127.2.3.4}

  http-server:
    build:
      context: ./http-server/
    ports:
      - "${DNSMASQ_RESOLUTION_IP:-127.2.3.4}:80:80"
    environment:
      - http_proxy

  https-server:
    build:
      context: ./https-server/
    ports:
      - "${DNSMASQ_RESOLUTION_IP:-127.2.3.4}:443:443"
    environment:
      - https_proxy
